services:
  redis:
    image: redis:alpine
    restart: always
    container_name: ${PROJECT_NAME}-redis
    volumes:
      - ./redis/data:/data
    ports:
      - "${REDIS_PORT}:6379"
    command: >
      --requirepass ${REDIS_PASSWORD}
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    networks:
      - local-network

  mysql:
    image: mysql:lts
    container_name: ${PROJECT_NAME}-mysql
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/db:/var/lib/mysql/
    networks:
      - local-network

  mysql_testing:
    image: mysql:lts
    container_name: ${PROJECT_NAME}-mysql_testing
    restart: unless-stopped
    ports:
      - "${MYSQL_TESTING_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_TESTING_DATABASE}
      MYSQL_USER: ${MYSQL_TESTING_USER}
      MYSQL_PASSWORD: ${MYSQL_TESTING_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_TESTING_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_testing
    command: mysqld --sql_mode="NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    tmpfs:
      - /var/lib/mysql:rw
    networks:
      - local-network

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGODB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_PASSWORD}'
      MONGO_INITDB_DATABASE=api: '${MONGODB_DATABASE}'
    ports:
      - '${MONGODB_PORT}:27017'
    networks:
      - local-network
    volumes:
      - ./mongo/db:/data/db/

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
      UPLOAD_LIMIT: 50M
    depends_on:
      - mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
    external: true
